pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'NeoForgeReleases'
            url = 'https://maven.neoforged.net/releases/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        mavenCentral()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'CodeChicken'
            url = 'https://maven.covers1624.net/'
        }
        maven {
            name = 'NeoForgeReleases'
            url = 'https://maven.neoforged.net/releases/'
        }
    }
}
